<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Error Message This page could not be found</name>
   <tag></tag>
   <elementGuidId>10e362b4-1a2d-4f1e-a1fb-13954c42ebc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4.MuiTypography-root.MuiTypography-h4.MuiTypography-alignCenter.css-16elfi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>6844ac72-c27d-4c14-ad45-e997a71a55bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h4 MuiTypography-alignCenter css-16elfi</value>
      <webElementGuid>bf978f9c-1d39-4db7-a6b5-9cd37129b44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This page could not be found.</value>
      <webElementGuid>5f92055e-1d43-4e9f-aae3-5d604bf6c36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiBox-root css-17e0a0a&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthMd css-oavo64&quot;]/h4[@class=&quot;MuiTypography-root MuiTypography-h4 MuiTypography-alignCenter css-16elfi&quot;]</value>
      <webElementGuid>edc3f82e-053c-4b54-9b26-d65bb1367e42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/h4</value>
      <webElementGuid>9971c1f6-98a9-4a8d-a547-6f375b2d9402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This page could not be found.']/parent::*</value>
      <webElementGuid>67b9c40a-ee47-42e6-9a23-388b4290f55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>f7fb57ce-e2d0-4353-89b8-ef5aa9a590a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'This page could not be found.' or . = 'This page could not be found.')]</value>
      <webElementGuid>242fe43b-3458-4f40-8fc2-5591f03039a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
